# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
                class: BackendBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forget_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/key_password, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/user_data, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/edit_user_data, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/sendKey, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/edit_password, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/remove, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/home, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/melody/remove, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/melody, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/stats, roles: [ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/delete_assest, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/music, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/like, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/unlike, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/score, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/follow, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/unfollow, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/following, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/followed, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/users_list, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/search, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/private_message, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/private_message/sended, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/private_message/notification/get, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/notifications, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/notifications/get, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        - { path: ^/contact, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_COMPOSER] }
        - { path: ^/activate, roles: [ROLE_USER, ROLE_ADMIN, ROLE_COMPOSER] }
        
