app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /
    
app_melody:
    resource: "@AppBundle/Resources/config/routing/melody.yml"
    prefix: /
    
app_social:
    resource: "@AppBundle/Resources/config/routing/social.yml"
    prefix: /
    
app_notification:
    resource: "@AppBundle/Resources/config/routing/notification.yml"
    prefix: /
    
app_private_message:
    resource: "@AppBundle/Resources/config/routing/private_message.yml"
    prefix: /

app_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix: /

app_homepage:
    path: /
    defaults: { _controller: AppBundle:User:login }
