BackendBundle\Entity\Assesment:
    type: entity
    table: assesments
    indexes:
        fk_assesments_users:
            columns:
                - user
        fk_assesments_melodies:
            columns:
                - melody
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        melody:
            targetEntity: Melody
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                melody:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
