BackendBundle\Entity\Melody:
    type: entity
    table: melodies
    indexes:
        fk_melodies:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        melody:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        status:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        creationDate:
            type: datetime
            nullable: true
            column: creation_date
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
