BackendBundle\Entity\PrivateMessage:
    type: entity
    table: private_messages
    indexes:
        fk_emitter_messages:
            columns:
                - emitter
        fk_receiver_messages:
            columns:
                - receiver
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        file:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        readed:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
        creationDate:
            type: datetime
            nullable: true
            column: creation_date
    manyToOne:
        emitter:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                emitter:
                    referencedColumnName: id
            orphanRemoval: false
        receiver:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                receiver:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
