BackendBundle\Entity\Score:
    type: entity
    table: scores
    indexes:
        fk_scores_users:
            columns:
                - user
        fk_scores_melodies:
            columns:
                - melody
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        score:
            type: integer
            nullable: true
            options:
                unsigned: false
        ponderedScore:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: pondered_score
    manyToOne:
        melody:
            targetEntity: Melody
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                melody:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
