BackendBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: BackendBundle\Repository\UserRepository
    uniqueConstraints:
        users_fields_unique:
            columns:
                - username
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        surname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        username:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        role:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        active:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        changepassword:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: changePassword
    lifecycleCallbacks: {  }
